services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - o11y-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - o11y
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=green&timeout=20s"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    image: grafana/grafana-enterprise:8.3.3
    ports:
      - "3333:3000"
    volumes:
      - o11y-grafana:/var/lib/grafana
    networks:
      - o11y

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - o11y-prometheus:/prometheus
    networks:
      - o11y

  jaeger:
    build:
      context: .
      dockerfile: Dockerfile.jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_ARCHIVE_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - o11y
    restart: on-failure
    depends_on:
      - elasticsearch

volumes:
  o11y-elasticsearch:
    name: o11y-elasticsearch
  o11y-grafana:
    name: o11y-grafana
  o11y-prometheus:
    name: o11y-prometheus

networks:
  o11y:
    name: o11y
